services:
  web:
    container_name: web
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./docker/development/caddy/conf/Caddyfile:/etc/caddy/Caddyfile
      - ./:/var/www
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal
    depends_on:
      app:
        condition: service_started

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/development/php-fpm/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: ${XDEBUG_MODE:-develop,coverage,debug,profile}
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: ${XDEBUG_LOG:-/dev/stdout}
        XDEBUG_LOG_LEVEL: ${XDEBUG_LOG_LEVEL:-0}
    env_file:
      - ./.env.dev
    volumes:
      - ./:/var/www
    networks:
      - internal
    healthcheck:
      test: [ "CMD-SHELL", "/usr/local/bin/php-fpm-healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
  queue-worker:
    container_name: queue-worker-development
    build:
      context: .
      dockerfile: ./docker/development/php-fpm/Dockerfile
    entrypoint: [ "sh", "-c", "php artisan queue:work --verbose --tries=3 --timeout=90" ]
    restart: unless-stopped
    volumes:
      - ./:/var/www/
    env_file:
      - ./.env.dev
    networks:
      - internal
    depends_on:
      reverb:
        condition: service_started

  workspace:
    container_name: workspace
    build:
      context: .
      dockerfile: ./docker/development/workspace/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: ${XDEBUG_MODE:-develop,coverage,debug,profile}
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: ${XDEBUG_LOG:-/dev/stdout}
        XDEBUG_LOG_LEVEL: ${XDEBUG_LOG_LEVEL:-0}
    ports:
      - '5173:5173'
    tty: true
    stdin_open: true
    volumes:
      - ./:/var/www
    networks:
      - internal
    env_file:
      - ./.env.dev
    depends_on:
      app:
        condition: service_started

  reverb:
    container_name: reverb
    build:
      context: .
      dockerfile: ./docker/development/php-fpm/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./:/var/www
    entrypoint: [ "sh", "-c", "php artisan reverb:start --host=0.0.0.0 --port=9000 --hostname='reverb' --debug" ]
    env_file:
      - ./.env.dev
    networks:
      - internal
    depends_on:
      app:
        condition: service_started

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - PGPASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data-development:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer:5
    restart: always
    ports:
      - "9080:8080"
    networks:
      - internal
    depends_on:
      postgres:
        condition: service_healthy

networks:
  internal:


volumes:
  postgres-data-development:
  caddy_data:
  caddy_config:
