services:
    web:
        build:
            context: .
            dockerfile: ./docker/production/nginx/Dockerfile
            args:
                - PUSHER_APP_KEY=${PUSHER_APP_KEY}
                - PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - uniespacos-storage-production:/var/www/storage:ro
            - uniespacos-public-assets:/var/www/public/build:ro
            - uniespacos-public-production:/var/www/public:ro
            # Chaves SSL para HTTPS
            - ./docker/production/nginx/uesb2025fullchain.pem:/etc/ssl/certs/uesb2025fullchain.pem:ro
            - ./docker/production/nginx/uesb2025privkey.pem:/etc/ssl/private/uesb2025privkey.pem:ro
        networks:
            - uniespacos-production
        depends_on:
            php-fpm:
                condition: service_healthy
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/common/php-fpm/Dockerfile
            target: production
        restart: unless-stopped
        volumes:
            - uniespacos-public-assets:/var/www/public/build
            - uniespacos-storage-production:/var/www/storage
            - uniespacos-public-production:/var/www/public
        env_file:
            - .env
        networks:
            - uniespacos-production
        healthcheck:
            test: [ "CMD-SHELL", "php-fpm-healthcheck || exit 1" ]
            interval: 10s
            timeout: 5s
            retries: 3
        depends_on:
            postgres:
                condition: service_healthy
    queue-worker:
        build:
            context: .
            dockerfile: ./docker/common/php-fpm/Dockerfile
            target: production
        restart: unless-stopped
        command: php artisan queue:work --verbose --tries=3 --timeout=90
        volumes:
            - uniespacos-storage-production:/var/www/storage
        env_file:
            - .env
        networks:
            - uniespacos-production
        depends_on:
            - postgres
            - php-fpm

    postgres:
        image: postgres:16
        restart: unless-stopped
        user: postgres
        ports:
            - "${DB_PORT:-5432}:5432"
        environment:
            - PGPASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - 'postgres-data-production:/var/lib/postgresql/data'
        networks:
            - uniespacos-production
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    uniespacos-production:


volumes:
    postgres-data-production:
    uniespacos-storage-production:
    uniespacos-public-assets:
    uniespacos-public-production:
