services:
    web:
        container_name: web-production
        image: caddy:alpine
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - uniespacos-storage-production:/var/www/storage:ro
            - uniespacos-public-assets-v2:/var/www/public/build:ro
            - uniespacos-public-production-v2:/var/www/public:ro
            - ./docker/production/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
            - /home/operador/app/docker/production/nginx/uesb2025fullchain.pem:/etc/caddy/certs/uesb2025fullchain.pem:ro
            - /home/operador/app/docker/production/nginx/uesb2025privkey.pem:/etc/caddy/certs/uesb2025privkey.pem:ro
            - caddy_data_production:/data
            - caddy_config_production:/config
        networks:
            - uniespacos-production
        depends_on:
            - app
    app:
        container_name: app-production
        image: ghcr.io/${GHCR_REPO_APP:-uniespacos/app/app}:${IMAGE_TAG:-latest}
        restart: unless-stopped
        volumes:
            - uniespacos-public-assets-v2:/var/www/public/build
            - uniespacos-public-production-v2:/var/www/public
            - uniespacos-storage-production:/var/www/storage
        env_file:
            - .env
        networks:
            - uniespacos-production
        depends_on:
            postgres:
                condition: service_healthy
    queue-worker:
        container_name: queue-worker-production
        image: ghcr.io/${GHCR_REPO_APP:-uniespacos/app/app}:${IMAGE_TAG:-latest}
        restart: unless-stopped
        command: php artisan queue:work --verbose --tries=3 --timeout=90
        volumes:
            - uniespacos-storage-production:/var/www/storage
        env_file:
            - .env
        networks:
            - uniespacos-production
        depends_on:
            - postgres
            - app

    reverb:
        container_name: reverb-production
        image: ghcr.io/${GHCR_REPO_APP:-uniespacos/app/app}:${IMAGE_TAG:-latest}
        restart: unless-stopped
        command: php artisan reverb:start --host=0.0.0.0 --port=9000
        ports:
            - "9000:9000"
        env_file:
            - .env
        networks:
            - uniespacos-production
        depends_on:
            - postgres
            - app

    postgres:
        container_name: postgres-production
        image: postgres:16
        restart: unless-stopped
        user: postgres
        ports:
            - "${DB_PORT:-5432}:5432"
        env_file:
            - .env
        environment:
            - PGPASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - 'postgres-data-production:/var/lib/postgresql/data'
        networks:
            - uniespacos-production
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 60s

networks:
    uniespacos-production:


volumes:
    postgres-data-production:
    uniespacos-storage-production:
    uniespacos-public-assets-v2:
    uniespacos-public-production-v2:
    caddy_data_production:
    caddy_config_production:
