services:
  web:
    container_name: web
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
    networks:
      - development
    depends_on:
      app:
        condition: service_started # Wait for app to start

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/development/php-fpm/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-false}
        XDEBUG_MODE: ${XDEBUG_MODE:-develop,debug}
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: ${XDEBUG_LOG:-/dev/stdout}
        XDEBUG_LOG_LEVEL: ${XDEBUG_LOG_LEVEL:-0}
        ENTRYPOINT_URI: ./docker/development/php-fpm/entrypoint-app.sh
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www
    networks:
      - development
    depends_on:
      postgres:
        condition: service_healthy
  queue-worker:
    container_name: queue-worker-development
    build:
      context: .
      dockerfile: ./docker/development/php-fpm/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-false}
        XDEBUG_MODE: ${XDEBUG_MODE:-develop,debug}
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: ${XDEBUG_LOG:-/dev/stdout}
        XDEBUG_LOG_LEVEL: ${XDEBUG_LOG_LEVEL:-0}
        ENTRYPOINT_URI: ./docker/development/php-fpm/entrypoint-worker.sh
    restart: unless-stopped
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    volumes:
      - ./:/var/www
    networks:
      - development
    depends_on:
      - postgres
      - app

  workspace:
    container_name: workspace
    build:
      context: .
      dockerfile: ./docker/development/workspace/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-false}
        XDEBUG_MODE: ${XDEBUG_MODE:-develop,debug}
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: ${XDEBUG_LOG:-/dev/stdout}
        XDEBUG_LOG_LEVEL: ${XDEBUG_LOG_LEVEL:-0}
        ENTRYPOINT_URI: ./docker/development/php-fpm/entrypoint-app.sh
    ports:
      - '${VITE_PORT:-5173}:5173'
    tty: true
    stdin_open: true
    volumes:
      - ./:/var/www
    networks:
      - development

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - PGPASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data-development:/var/lib/postgresql/data
    networks:
      - development
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer:5
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - development

networks:
  development:


volumes:
  postgres-data-development:
