services:
    web:
        container_name: web-staging
        image: caddy:alpine
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "80:80"
        volumes:
            - uniespacos-storage-staging:/var/www/storage:ro
            - uniespacos-public-assets-v2-staging:/var/www/public/build:ro
            - uniespacos-public-staging-v2:/var/www/public:ro
            - ./docker/staging/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
            - caddy_data_staging:/data
            - caddy_config_staging:/config
        networks:
            - uniespacos-staging
        depends_on:
            - app
    app:
        container_name: app-staging
        image: ghcr.io/${GHCR_REPO_APP:-uniespacos/app/app}:${IMAGE_TAG:-latest}
        restart: unless-stopped
        volumes:
            - uniespacos-public-assets-v2-staging:/var/www/public/build
            - uniespacos-public-staging-v2:/var/www/public
            - uniespacos-storage-staging:/var/www/storage
        env_file:
            - .env
        networks:
            - uniespacos-staging
        depends_on:
            postgres:
                condition: service_healthy
    queue-worker:
        container_name: queue-worker-staging
        image: ghcr.io/${GHCR_REPO_APP:-uniespacos/app/app}:${IMAGE_TAG:-latest}
        restart: unless-stopped
        command: php artisan queue:work --verbose --tries=3 --timeout=90
        volumes:
            - uniespacos-storage-staging:/var/www/storage
        env_file:
            - .env
        networks:
            - uniespacos-staging
        depends_on:
            - postgres
            - app

    reverb:
        container_name: reverb-staging
        image: ghcr.io/${GHCR_REPO_APP:-uniespacos/app/app}:${IMAGE_TAG:-latest}
        restart: unless-stopped
        command: php artisan reverb:start --host=0.0.0.0 --port=9000
        ports:
            - "9000:9000"
        env_file:
            - .env
        networks:
            - uniespacos-staging
        depends_on:
            - postgres
            - app

    postgres:
        container_name: postgres-staging
        image: postgres:16
        restart: unless-stopped
        user: postgres
        ports:
            - "${DB_PORT:-5432}:5432"
        env_file:
            - .env
        environment:
            - PGPASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - 'postgres-data-staging:/var/lib/postgresql/data'
        networks:
            - uniespacos-staging
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 60s

networks:
    uniespacos-staging:

volumes:
    postgres-data-staging:
    uniespacos-storage-staging:
    uniespacos-public-assets-v2-staging:
    uniespacos-public-staging-v2:
    caddy_data_staging:
    caddy_config_staging:
